config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#new'
  resources :tweets, only: [:new, :create] do
    collection do
      get 'post'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :twitter_client, except: :new

    def new
      @tweet = Tweet.new
    end

    def create
        Tweet.create(create_params)
        redirect_to :root
    end

    def post
        t = Datetime.zone
        puts "#{t}"
        #tweet = Tweet.where(day: Date.today.strftime("%m%d")).first
        tweet = Tweet.where(day: t.tomorrow.strftime("%m%d")).first
        tweet2 = Tweet.where(day: t.since(7.days).strftime("%m%d")).first
        tweet3 = Tweet.where(day: t.next_month.strftime("%m%d")).first
        puts "#{tweet}"
        puts "#{tweet2}"
        puts "#{tweet3}"
        status = tweet.text
        status2 = tweet2.text
        status3 = tweet3.text
        #response = @client.update(status)
        response = @client.update("明日#{t.tomorrow.strftime("%m")}月#{t.tomorrow.strftime("%d")}日は　#{status}です。\r1週間後#{t.since(7.days).strftime("%m")}月#{t.since(7.days).strftime("%d")}日は　#{status2}です。\r1ヶ月後#{t.next_month.strftime("%m")}月#{t.next_month.strftime("%d")}日は　#{status3} です。 ")
        #response = @client.update("#{status} と地の文")
        #Rails.logger.debug response
        redirect_to :root
    end
    
    def twitter_client
        @client = Twitter::REST::Client.new do |config|
          config.consumer_key = ENV['CONSUMER_KEY']
          config.consumer_secret = ENV['CONSUMER_SECRET']
          config.access_token = ENV['ACCESS_TOKEN']
          config.access_token_secret = ENV['ACCESS_TOKEN_SECRET']
        end
    end

      private
      def create_params
        params.require(:tweet).permit(:text, :image, :day)
      end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twibot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/new.html.erb
<%= form_for @tweet do |f| %>
    <%= f.text_area :text, cols: 40, rows: 5 ,maxlength: 140 %>
    <%= f.text_field :day %>
    <%= f.submit '保存' %>
  <% end %>
  <hr>
<button type="submit" style = "width: 70px; height: 25px;"><%= link_to 'ツイート', post_tweets_path %></button>
<hr>
<a href="https://px.a8.net/svt/ejp?a8mat=3598PP+DE94S2+2Z0I+CGTEP" target="_blank" rel="nofollow">
<img border="0" width="300" height="250" alt="" src="https://www23.a8.net/svt/bgt?aid=190227805810&wid=001&eno=01&mid=s00000013869002094000&mc=1"></a>
<img border="0" width="1" height="1" src="https://www19.a8.net/0.gif?a8mat=3598PP+DE94S2+2Z0I+CGTEP" alt="">